# Generated by Django 4.1.3 on 2022-12-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_auto_20200426_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('name', models.TextField()),
                ('content', models.TextField(default='A new content added')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
