# Generated by Django 4.1.3 on 2022-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='content',
            field=models.CharField(default='A new content added', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='path',
            field=models.TextField(max_length=200),
        ),
    ]
