# Generated by Django 4.1.3 on 2022-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_alter_upload_content_alter_upload_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='createdat',
            field=models.DateTimeField(),
        ),
    ]
