# Generated by Django 4.1.3 on 2022-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_alter_upload_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='video',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
