# Generated by Django 4.1.3 on 2022-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('name', models.TextField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
