# Generated by Django 4.1.3 on 2022-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='content',
            field=models.TextField(default='A new content added'),
        ),
    ]
