# Generated by Django 4.1.3 on 2022-12-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_upload_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
